version: '3'

services:
  posterr:
    image: node:latest
    command: yarn start
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/usr/src/app/posterr
    working_dir: /usr/src/app/posterr
    networks:
      - mongo-compose-network
    links:
      - mongo
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  mongo-express:
    container_name: mongoExpress
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongoDB
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_BASIC_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_BASIC_PASSWORD}
      ME_CONFIG_MONGODB_PORT: ${DB_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_ROOT_PASSWORD}
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    container_name: mongoDB
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:27017
    networks:
      - mongo-compose-network

networks:
    mongo-compose-network:
      driver: bridge
